name: Compilar APK Android

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repositorio sin bloquearse si hay submódulos inaccesibles
      - name: Descargar código fuente
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      # 2. Inicializar submódulos manualmente con tolerancia a fallos
      - name: Inicializar submódulos de Git
        run: |
          git submodule init
          git submodule update --recursive || true

      # 3. Configurar entorno Java 17
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. Configurar Android SDK y NDK para compilar C++
      - name: Configurar NDK y Android SDK
        uses: android-actions/setup-android@v3

      # 5. Otorgar permisos de ejecución al script de Gradle
      - name: Dar permisos de ejecución a Gradlew
        run: chmod +x gradlew

      # 6. Ejecutar la compilación de la APK en modo Debug
      - name: Compilar APK Debug
        run: ./gradlew assembleDebug --no-daemon

      # 7. Exportar la APK generada a la sección de Artefactos de GitHub
      - name: Subir APK lista para descargar
        uses: actions/upload-artifact@v4
        with:
          name: xmrig-android-debug
          path: app/build/outputs/apk/debug/*.apk
